on:
  push:
    branches:
      - "!master"
  pull_request:

name: CI
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run
        run: ./container.sh